export const SINGLE_CAR = 'http://localhost:5001/api/cars/singlecar/'
export const CREATE_USER_API = 'http://localhost:5001/api/user/my'
export const GET_USER_API = 'http://localhost:5001/api/user/getuser'
export const ADD_TO_WATCH_LIST= 'http://localhost:5001/api/watch/add-to-watch-list'
export const REMOVE_FROM_WATCH_LIST ='http://localhost:5001/api/watch/remove-from-watch-list'
export const CHECK_CAR_IN_WATCH_LIST='http://localhost:5001/api/watch/check-car-watch-list'
export const GET_MY_WATCH_LIST_CARS = 'http://localhost:5001/api/watch/get-my-watch-list-cars'
